# Generated by Django 4.0.4 on 2022-09-12 12:00

import birthday.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('cover', models.ImageField(help_text='Songs cover', upload_to='tracks', verbose_name='Cover')),
                ('upload_date', models.DateTimeField(default=datetime.date, verbose_name='Upload date')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='Nickname')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Surname')),
                ('image', models.ImageField(help_text='Photo', upload_to='artists/<django.db.models.fields.CharField>', verbose_name='Image')),
                ('bio', models.CharField(blank=True, max_length=256, null=True, verbose_name='Bio')),
                ('birthday_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('birthday', birthday.fields.BirthdayField(verbose_name='Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ib_title', models.CharField(blank=True, help_text='Name', max_length=64, null=True, verbose_name='Title')),
                ('ib_image', models.ImageField(help_text='Photo', upload_to='intro_banner', verbose_name='Image')),
                ('ab_title', models.CharField(blank=True, help_text='About', max_length=64, null=True, verbose_name='Title')),
                ('ab_description', models.CharField(blank=True, help_text='About', max_length=256, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Index page',
                'verbose_name_plural': 'Index page',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('lyrics', models.TextField(blank=True, help_text='Song lyrics', null=True, verbose_name='Lyrics')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caspermun.album', verbose_name='Album')),
                ('artist', models.ManyToManyField(related_name='Artist', to='caspermun.artist', verbose_name='Artist')),
                ('sound_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caspermun.artist', verbose_name='Sound producer')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caspermun.artist', verbose_name='Artist'),
        ),
    ]
