# Generated by Django 4.0.4 on 2022-09-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='logo',
            field=models.FileField(blank=True, help_text='Logo', null=True, upload_to='logo', verbose_name='Logo'),
        ),
    ]
