# Generated by Django 4.0.4 on 2022-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0002_indexpage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='ab_description',
            field=models.CharField(blank=True, help_text='About', max_length=512, null=True, verbose_name='Description'),
        ),
    ]
