# Generated by Django 4.0.4 on 2022-09-13 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0003_alter_indexpage_ab_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.date(2022, 9, 13), verbose_name='Upload date'),
        ),
    ]
