# Generated by Django 4.0.4 on 2022-09-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0004_alter_album_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='upload_date',
        ),
    ]
