# Generated by Django 4.0.4 on 2022-09-13 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0006_alter_album_options_album_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 12, 47, 52, 586359), verbose_name='Upload date'),
        ),
    ]
