# Generated by Django 4.0.4 on 2022-09-13 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0007_alter_album_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f6cec7564d0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(help_text='Songs cover', upload_to='tracks/<django.db.models.fields.CharField>', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 12, 57, 57, 407055), verbose_name='Upload date'),
        ),
    ]
