# Generated by Django 4.0.4 on 2022-09-13 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0009_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 15, 48, 52, 471934), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f9e67f36500>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
