# Generated by Django 4.0.4 on 2022-09-14 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0012_remove_album_center_remove_album_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.CharField(blank=True, help_text='Url title', max_length=64, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 11, 6, 41, 508469), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fccccf52560>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
