# Generated by Django 4.0.4 on 2022-09-14 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0013_album_url_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('url', models.URLField(help_text='Url', verbose_name='Url')),
                ('logo', models.FileField(help_text='Logo', upload_to='url_logos', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 11, 17, 4, 374785), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f3938f525c0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
