# Generated by Django 4.0.4 on 2022-09-14 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0014_link_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Album', null=True, on_delete=django.db.models.deletion.CASCADE, to='caspermun.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 11, 21, 6, 577625), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f12eb14a5c0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
