# Generated by Django 4.0.4 on 2022-09-14 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0016_alter_album_upload_date_alter_link_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 13, 43, 41, 733068), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='ab_title',
            field=models.CharField(blank=True, help_text='About', max_length=512, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f12431565c0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
