# Generated by Django 4.0.4 on 2022-09-14 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0017_alter_album_upload_date_alter_indexpage_ab_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='c_banner',
            field=models.ImageField(blank=True, help_text='Photo', null=True, upload_to='contact_banner', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_email',
            field=models.URLField(blank=True, max_length=64, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_insta',
            field=models.URLField(blank=True, max_length=64, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_telegram',
            field=models.URLField(blank=True, max_length=64, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 14, 42, 15, 354735), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fda5e736a10>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
