# Generated by Django 4.0.4 on 2022-09-15 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0018_indexpage_c_banner_indexpage_c_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 12, 22, 1, 202235), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7ff22bb4ab60>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
