# Generated by Django 4.0.4 on 2022-09-15 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0020_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 12, 56, 19, 761436), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='album',
            name='url',
            field=models.CharField(help_text='Url title', max_length=64, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fa0e134ac20>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
