# Generated by Django 4.0.4 on 2022-09-15 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0023_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 13, 12, 9, 492090), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo', null=True, upload_to='artists/<django.db.models.fields.CharField>', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='ab_description',
            field=models.CharField(help_text='About', max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='ab_title',
            field=models.CharField(help_text='About', max_length=512, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_banner',
            field=models.ImageField(help_text='Photo', upload_to='contact_banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_email',
            field=models.URLField(max_length=64, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_insta',
            field=models.URLField(max_length=64, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_telegram',
            field=models.URLField(max_length=64, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='ib_title',
            field=models.CharField(help_text='Name', max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='logo',
            field=models.FileField(help_text='Logo', upload_to='logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='link',
            name='album',
            field=models.ForeignKey(help_text='Album', on_delete=django.db.models.deletion.CASCADE, to='caspermun.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7ff66113ac50>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
