# Generated by Django 4.0.4 on 2022-09-15 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0024_alter_album_upload_date_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='ab_banner',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='About image'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 13, 16, 19, 306332), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_banner',
            field=models.ImageField(help_text='Photo', upload_to='contact_banner', verbose_name='Contact banner'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='ib_image',
            field=models.ImageField(help_text='Photo', upload_to='intro_banner', verbose_name='Intro image'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f6a27b3ad40>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
