# Generated by Django 4.0.4 on 2022-09-16 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0027_indexpage_bg_image_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 21, 59, 55, 588479), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fc2c5d52c80>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
