# Generated by Django 4.0.4 on 2022-09-17 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0028_album_views_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='c_email',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_booking',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Booking'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_deal',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 18, 56, 23, 970293), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fc167936f20>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
