# Generated by Django 4.0.4 on 2022-09-17 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0029_remove_indexpage_c_email_indexpage_c_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='c_facebook',
            field=models.URLField(blank=True, max_length=64, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_youtube',
            field=models.URLField(blank=True, max_length=64, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 19, 33, 4, 754369), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f9f40d53160>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
