# Generated by Django 4.0.4 on 2022-09-17 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0030_indexpage_c_facebook_indexpage_c_youtube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 3, 49, 56, 257208), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_booking',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='c_deal',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fd638137160>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
