# Generated by Django 4.0.4 on 2022-09-17 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0031_alter_album_upload_date_alter_indexpage_c_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='c_facebook',
        ),
        migrations.AddField(
            model_name='indexpage',
            name='c_tiktok',
            field=models.URLField(blank=True, max_length=64, null=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 4, 9, 23, 467278), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f6c77153160>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
