# Generated by Django 4.0.4 on 2022-09-20 08:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0040_about_artist_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caspermun.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 14, 23, 52, 178812), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(help_text='Shows in about page', max_length=2048, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fafd07536d0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
