# Generated by Django 4.0.4 on 2022-09-20 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0041_alter_about_artist_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 17, 47, 1, 526452), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7fc3009854e0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
