# Generated by Django 4.1.1 on 2022-09-20 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0047_artist_bio_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 2, 25, 42, 974770), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(default='', help_text='Shows in about page', max_length=2048, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f0646f584c0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
