# Generated by Django 4.1.1 on 2022-09-21 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0048_alter_album_upload_date_alter_artist_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 20, 51, 16, 677384), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f3dd4b6d540>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
