# Generated by Django 4.1.1 on 2022-09-26 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0050_alter_album_upload_date_alter_artist_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='explicit',
            field=models.BooleanField(default=False, verbose_name='Explicit'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 10, 27, 12, 529656), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f51f714c880>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
