# Generated by Django 4.1.1 on 2022-09-26 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0051_track_explicit_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='explicit',
            field=models.BooleanField(default=False, verbose_name='Explicit'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('hh', 'Hip-Hop/Rap'), ('trap', 'Trap'), ('rb', 'R&B'), ('pop', 'Pop')], default='hh', max_length=64, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 2, 20, 41, 310117), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f1aa4758970>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
