# Generated by Django 4.1.1 on 2022-09-27 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0052_album_explicit_album_genre_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Track duration'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 52, 10, 505863), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7ff15ed76d10>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
