# Generated by Django 4.1.1 on 2022-10-26 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0055_remove_track_duration_alter_album_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='html',
            field=models.TextField(default='', help_text='Embed code', verbose_name='Apple Music'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 12, 40, 1, 91083), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f489975ed40>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
