# Generated by Django 4.1.1 on 2022-10-26 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caspermun', '0056_album_html_alter_album_upload_date_alter_track_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='html',
            field=models.URLField(default='', help_text='Embed code', verbose_name='Apple Music'),
        ),
        migrations.AlterField(
            model_name='album',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 12, 42, 10, 962666), verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, help_text='Track', max_length=1000, null=True, upload_to='tracks/<django.db.models.query_utils.DeferredAttribute object at 0x7f0da8176da0>/<django.db.models.fields.CharField>', verbose_name='Audio'),
        ),
    ]
